version: '3.5'
services:
  app:
    container_name: docker-node-mongo
    restart: on-failure # If it fails, simply restart the container
    build: . # Looks at the current directory for the Dockerfile to build the image
    ports:
      - '80:3000'
    depends_on:
      - mongo # Depends on the mongo container to run before running this container, this doesn't necessarily mean it will wait for mongo to start
  mongo:
    container_name: mongo
    image: mongo # Define the mongo image since we're not building from a Dockerfile for the mongo service, so it'll pull from DockerHub
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db # Persists our MongoDB data in the /data/db folder